### ISSUE TITLE
Microsoft Edge query selector 

### ISSUE THREAD

**Issue by H3dz** [RoXuS/paper-datatable-api#20]
Currently, paper-datable-api can't be used with Edge.

If you look at the demo everything freezes and the data is never displayed.

A query selector in DtPaperDatatableApi::_handleActiveFilterChange seems to be the cause of the problem.

If you remove ":scope" from the selector everything works.

I also found 2 other solutions.
Move
`let paperInput = parentDiv.querySelector(':scope > paper-input');`
outside of this.async

or add wait=1 to the this.async

I didn't create a pull request because I couldn't find the real reason why :scope would make everything break in Edge.

**Comment by RoXuS** [comment]
Hello !

It doesn't work on Edge because it is an experimental feature and it Edge does not support it.

I don't remember why I have used this feature but it seems to be useless now.

Thx for the bug, can you tell me if it is ok on your Edge, on the master branch (see this commit https://github.com/RoXuS/paper-datatable-api/commit/02dba1c67a1309667ce0695cd31bc2343e134096).

**Comment by H3dz** [comment]
Yes, that fixed it.

Thanks
